name: Build and Push to GHCR

on:
  push:
    branches:
      - main # O build será feito sempre que houver um push na branch main. Pode mudar para 'master' se for o caso.

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Isso dá permissão para o GitHub Actions enviar arquivos para o GHCR
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login na nuvem nativa do GitHub
      - name: Log in to the Container registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # ← Você NÃO precisa criar esse token, o GitHub passa ele sozinho.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Constrói a imagem passando as variáveis pro Next.js e joga no GHCR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # A imagem ficará no formato: ghcr.io/eliasglaucio/nome-do-repositorio:latest
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
